### ISSUE TITLE
Youtube history issue

### ISSUE THREAD

**Issue by destiny159** [jere53/JFJCompiler#1]
Hi there @jere53 I've seen your issue on https://github.com/night/betterttv/issues/5374

I have the same issue at the moment. Even the same type of videos. Did you manage to find out the reason why it happened and maybe how to fix it? 
Sorry for contacting you this way, but this thing has been driving me nuts.

**Comment by jere53** [comment]
Yes, it was one of the browser extensions. Initially I suspected better TTV because it only happened while it was enabled, but after more tests it turned out that it was a different one, I can't exactly remember which. Disabling all extensions then turning them on one by one to find which is causing the issue, then uninstalling that one, solved the problem for me. Sometimes it takes a while for the videos to show up even with the problematic extension enabled, it might not even happen at all hours of the day from what I saw. I'd advise you disable them all, then turn on one each day and see if at the end of the day you still get the videos. If you don't, then try the next one.
